export const CELEBS = [
  { id:1, name:"Christopher Larosa", country:"Canada", flag:"🇨🇦", price:5000, rating:4.9, reviews:128, cat:"actors", img:"https://stratifymanagementteam.com/admin/storage/app/public/uploads/69bad611a58b9.jpg", bio:"Award-winning Canadian actor celebrated for his intense dramatic roles in both film and television. Known for his extraordinary range and commitment to authentic storytelling.", feat:true, avail:true, tags:["Corporate Events","Charity Galas","Film Premieres","Speaking"] },
  { id:2, name:"Hamdan Al Maktoum", country:"UAE", flag:"🇦🇪", price:18500, rating:4.9, reviews:89, cat:"royalty", img:"https://stratifymanagementteam.com/admin/storage/app/public/uploads/691303dc8c54e.jpg", bio:"Crown Prince of Dubai, accomplished equestrian champion, beloved poet, and global philanthropist whose presence commands respect and admiration worldwide.", feat:true, avail:true, tags:["State Events","Equestrian Shows","Charity","Exclusive"] },
  { id:3, name:"Anthony Dalton", country:"USA", flag:"🇺🇸", price:7000, rating:4.9, reviews:203, cat:"actors", img:"https://stratifymanagementteam.com/admin/storage/app/public/uploads/69bae06bb2105.jpg", bio:"Hollywood producer and actor with decades of experience spanning blockbuster films and award-winning television.", feat:true, avail:false, tags:["Screenings","Q&A Sessions","Award Shows","Private Functions"] },
  { id:4, name:"Noah Fearnley", country:"Australia", flag:"🇦🇺", price:4500, rating:4.9, reviews:156, cat:"musicians", img:"https://stratifymanagementteam.com/admin/storage/app/public/uploads/69bcefbce7072.jpeg", bio:"Chart-topping Australian musician whose soulful compositions have earned him international acclaim and a dedicated global fanbase.", feat:true, avail:true, tags:["Live Concerts","Private Performances","Meet & Greet","Radio"] },
  { id:5, name:"Espen Hatleskog", country:"Australia", flag:"🇦🇺", price:6000, rating:4.9, reviews:97, cat:"sports", img:"https://stratifymanagementteam.com/admin/storage/app/public/uploads/69bcf0390bb6d.jpeg", bio:"Professional athlete and motivational speaker who has inspired millions through his extraordinary sporting achievements.", feat:true, avail:true, tags:["Motivational Talks","Sports Events","Brand Appearances","Coaching"] },
  { id:6, name:"Aria Chen", country:"Singapore", flag:"🇸🇬", price:8500, rating:4.8, reviews:174, cat:"musicians", img:null, bio:"Grammy-nominated pop artist from Singapore whose cross-cultural sound has captivated audiences worldwide.", feat:false, avail:true, tags:["Concert Tours","TV Appearances","Fan Experiences","Brand Deals"] },
  { id:7, name:"Marcus Webb", country:"UK", flag:"🇬🇧", price:12000, rating:4.7, reviews:211, cat:"actors", img:null, bio:"BAFTA award-winning British actor renowned for transformative roles in critically acclaimed dramas.", feat:false, avail:true, tags:["Theatre Events","Film Festivals","Private Functions","Keynotes"] },
  { id:8, name:"Layla Hassan", country:"Egypt", flag:"🇪🇬", price:6500, rating:4.8, reviews:342, cat:"influencers", img:null, bio:"Digital creator with 50M+ followers — one of the most influential voices in the Arab world.", feat:false, avail:false, tags:["Brand Campaigns","Product Launches","Social Media","Endorsements"] },
  { id:9, name:"Diego Santos", country:"Brazil", flag:"🇧🇷", price:9000, rating:4.9, reviews:189, cat:"sports", img:null, bio:"Olympic gold medalist and fitness icon inspiring youth worldwide through sports and wellness advocacy.", feat:false, avail:true, tags:["Sports Clinics","Fitness Events","School Visits","Keynotes"] },
  { id:10, name:"Yuki Tanaka", country:"Japan", flag:"🇯🇵", price:7500, rating:4.8, reviews:267, cat:"influencers", img:null, bio:"Fashion influencer and brand ambassador whose unique aesthetic sense has shaped global trends.", feat:false, avail:true, tags:["Fashion Shows","Brand Deals","Cultural Events","Exhibitions"] },
  { id:11, name:"Sofia Reyes", country:"Mexico", flag:"🇲🇽", price:5500, rating:4.7, reviews:145, cat:"musicians", img:null, bio:"Latin pop sensation with vibrant personality and chart-topping hits loved across the globe.", feat:false, avail:true, tags:["Concerts","Festivals","Fan Meetups","Brand Events"] },
  { id:12, name:"James Okafor", country:"Nigeria", flag:"🇳🇬", price:4000, rating:4.8, reviews:312, cat:"actors", img:null, bio:"Nollywood icon and international star whose work bridges African storytelling with global cinema.", feat:false, avail:true, tags:["Film Events","Cultural Shows","Speaking","Charity"] },
];

export const CATS = [
  { id:"actors", name:"Actors & Actresses", n:"200+", icon:"🎬", desc:"Hollywood stars, TV personalities, award-winning performers" },
  { id:"musicians", name:"Musicians & Artists", n:"180+", icon:"🎵", desc:"Chart-toppers, bands, recording artists for live performances" },
  { id:"sports", name:"Sports Stars", n:"150+", icon:"🏆", desc:"Athletes, Olympians, and legendary sports figures" },
  { id:"influencers", name:"Digital Influencers", n:"250+", icon:"✨", desc:"Social media stars, content creators, digital personalities" },
  { id:"royalty", name:"Royalty & Dignitaries", n:"50+", icon:"👑", desc:"Royal family members and distinguished world dignitaries" },
];

export const SERVICES = [
  { icon:"📅", title:"Celebrity Bookings", desc:"Book celebrities for your event with transparent pricing, availability calendars, and a secure payment gateway.", cta:"Book Now" },
  { icon:"🎥", title:"Video Messages", desc:"Personalized HD video messages from your favorite celebrities for birthdays, anniversaries, or any special occasion.", cta:"Request Video" },
  { icon:"🤝", title:"Meet & Greet", desc:"Exclusive in-person meet & greet packages complete with photo opportunities, autograph sessions, and VIP access.", cta:"Reserve Now" },
  { icon:"💎", title:"VIP Fan Card", desc:"Unlock priority booking, exclusive content, special discounts, and personalized birthday surprises from celebrities.", cta:"Apply Now" },
  { icon:"🎤", title:"Motivational Talks", desc:"Book celebrities for keynote speeches, corporate motivationals, school visits, and community outreach.", cta:"Enquire" },
  { icon:"🎁", title:"Custom Experience", desc:"Bespoke celebrity experiences crafted specifically for your event — from intimate dinners to brand activations.", cta:"Get Quote" },
];

export const TESTIMONIALS = [
  { name:"James Richardson", role:"Event Director, London", text:"Booked a celebrity for our corporate gala and the experience was absolutely flawless. The team handled every detail professionally.", stars:5 },
  { name:"Emily Hartwell", role:"Repeat Client, New York", text:"I've used StarBookNow three times now and it never disappoints. The process is seamless, the celebrities always deliver.", stars:5 },
  { name:"Felix Andersen", role:"Brand Manager, Copenhagen", text:"Organized a meet & greet for 500 fans and everything was perfectly coordinated. Outstanding service!", stars:5 },
  { name:"Charlotte Beaumont", role:"PR Director, Paris", text:"StarBookNow transformed our product launch into an unforgettable evening. The celebrity they matched us with was the perfect fit.", stars:5 },
  { name:"David Thornton", role:"CEO, Thornton Group, Dubai", text:"We've partnered with StarBookNow for three consecutive annual galas. Their professionalism and A-list roster is unmatched.", stars:5 },
  { name:"Sophie Laurent", role:"Wedding Planner, Milan", text:"My client wanted a surprise celebrity appearance and StarBookNow made the impossible happen in just two weeks.", stars:5 },
];

export const BLOGS = [
  {
    id: 1,
    title: "How to Plan the Perfect Celebrity Appearance at Your Corporate Event",
    slug: "plan-celebrity-corporate-event",
    category: "Event Planning",
    author: "James Whitfield",
    authorRole: "Senior Booking Concierge",
    date: "2026-03-10",
    readTime: "7 min read",
    feat: true,
    img: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80",
    excerpt: "A celebrity appearance can elevate a corporate event from routine to legendary — but only when the logistics are right. Here's how the pros do it.",
    content: [
      { type: "p", text: "Booking a celebrity for your corporate event is one of the most powerful moves an event organizer can make. The right star turns a standard gala into a headline moment — one that employees talk about for years. But pulling it off flawlessly requires careful planning, realistic timelines, and a partner who knows the industry inside out." },
      { type: "h2", text: "Start 3–6 Months in Advance" },
      { type: "p", text: "Top-tier celebrities are booked months ahead of schedule. The moment you know your event date, start your search. Waiting until six weeks out severely limits your options and often inflates cost. Our concierge team recommends locking in talent at least 90 days before your event." },
      { type: "h2", text: "Define Your Objective First" },
      { type: "p", text: "Are you trying to boost morale, attract press, launch a product, or reward clients? The answer shapes everything — which celebrity, what format (keynote, performance, Q&A), and how much stage time is needed. A misaligned booking wastes budget and underwhelms your audience." },
      { type: "h2", text: "Respect the Rider" },
      { type: "p", text: "Every professional celebrity has a rider — a document listing technical, logistical, and personal requirements. This isn't diva behavior; it's professionalism. Your venue needs to accommodate these requests to ensure the talent can deliver their best. StarBookNow's team reviews riders and negotiates on your behalf to keep requirements practical." },
      { type: "h2", text: "Brief the Celebrity Thoroughly" },
      { type: "p", text: "The best appearances feel personal. Share your company story, key messages, and audience demographics with the talent well ahead of the event. Great celebrities use this to tailor their appearance — mentioning your brand milestones, acknowledging your team, making the moment feel genuine rather than transactional." },
      { type: "h2", text: "Prepare for Day-Of Logistics" },
      { type: "p", text: "Assign a dedicated point-of-contact for the talent on the day. Ensure transport, green room access, and timing are locked down. Buffer 30 minutes before the celebrity's slot for any last-minute needs. Nothing undermines a great appearance like rushed logistics at the end." },
      { type: "p", text: "When you work with StarBookNow, our concierge handles all of this coordination from contract to curtain call. Your job is to enjoy the moment." },
    ],
  },
  {
    id: 2,
    title: "The Rise of the Video Message: Why Personalized Celebrity Shoutouts Are the New Luxury Gift",
    slug: "celebrity-video-messages-luxury-gift",
    category: "Trends",
    author: "Priya Mehta",
    authorRole: "Head of Client Experience",
    date: "2026-02-28",
    readTime: "5 min read",
    feat: true,
    img: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&q=80",
    excerpt: "In a world of same-day delivery and digital gifting, nothing cuts through like a personal video from an icon. We explore why celebrities messages have become the most-requested service on the platform.",
    content: [
      { type: "p", text: "Imagine receiving a birthday greeting not from a friend, but from your all-time favourite athlete. Or your company's top performer getting a personalised congratulations from a celebrity they admire. That is the power of the celebrity video message — and it has quietly become our fastest-growing service." },
      { type: "h2", text: "Why It Works" },
      { type: "p", text: "Scarcity creates value. When someone receives a personalised video from a celebrity, the implicit message is: someone cared enough to make this happen. It's not something you can buy off a shelf. It requires effort, access, and intention — three things that signal deep appreciation." },
      { type: "h2", text: "The Corporate Angle" },
      { type: "p", text: "Forward-thinking HR and leadership teams have discovered that celebrity messages are extraordinary motivational tools. A video shoutout celebrating a promotion, a work anniversary, or a sales target hit creates a memory the recipient never forgets. It's far more impactful than a gift card — and often less expensive." },
      { type: "h2", text: "What Makes a Great Video Message" },
      { type: "p", text: "The best celebrity messages are specific. Vague generic shoutouts land flat. When briefing the talent, include the recipient's name, why they're being celebrated, a personal detail or two, and the tone you want (heartfelt, humorous, motivational). The celebrity will craft something that feels made-for-them — because it is." },
      { type: "h2", text: "Turnaround and Quality" },
      { type: "p", text: "StarBookNow's video message service delivers in HD within 7 business days. For premium requests, express 48-hour delivery is available. Every video is reviewed for quality before delivery. If it doesn't meet our standards, we request a reshoot at no cost to you." },
    ],
  },
  {
    id: 3,
    title: "5 Celebrity Keynote Speakers Who Are Redefining the Conference Stage",
    slug: "celebrity-keynote-speakers-2026",
    category: "Insights",
    author: "Marcus Cole",
    authorRole: "Talent Relations Director",
    date: "2026-02-14",
    readTime: "6 min read",
    feat: false,
    img: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&q=80",
    excerpt: "The era of the dull conference keynote is over. These five names are turning corporate stages into must-see moments — and the attendee satisfaction scores prove it.",
    content: [
      { type: "p", text: "Conference keynotes have a reputation problem. Attendees dread the post-lunch slot. Engagement drops. Phones come out. But something has shifted — event organizers who book celebrities with genuine expertise in leadership, resilience, or innovation are seeing attendance and satisfaction metrics hit record highs." },
      { type: "h2", text: "What Separates a Speaker from a Star Speaker" },
      { type: "p", text: "The difference isn't fame — it's story. Celebrities who have navigated extreme pressure, built empires from scratch, or overcome public adversity carry lessons that resonate with business audiences in a way that career speakers simply cannot replicate. Authenticity, drama, and real stakes make for unforgettable content." },
      { type: "h2", text: "Matching the Speaker to the Room" },
      { type: "p", text: "A motivational athlete works brilliantly for a sales conference. A philanthropist-entrepreneur resonates with CSR-focused leadership teams. A creative icon fits a brand or marketing summit. The match between speaker ethos and audience identity is the single biggest determinant of keynote success. StarBookNow's matching engine uses your event brief to surface exactly the right options." },
      { type: "h2", text: "Format Matters" },
      { type: "p", text: "The traditional 45-minute talk is no longer the gold standard. Fireside chats, moderated Q&As, and workshop-style sessions with celebrity co-facilitators are outperforming solo presentations on almost every engagement metric. Consider building interactivity into the format from the start." },
    ],
  },
  {
    id: 4,
    title: "Behind the Scenes: What Actually Happens When You Make a Booking",
    slug: "behind-the-scenes-booking-process",
    category: "How It Works",
    author: "James Whitfield",
    authorRole: "Senior Booking Concierge",
    date: "2026-01-30",
    readTime: "4 min read",
    feat: false,
    img: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80",
    excerpt: "Most clients see a confirmation email. We show you everything that happens in between — the calls, the negotiations, the logistics, and the moments when it all comes together.",
    content: [
      { type: "p", text: "When you submit a booking request on StarBookNow, you see a clean interface and a confirmation notification. What you don't see is the flurry of activity that begins the moment your request lands in our system." },
      { type: "h2", text: "Step 1: Talent Assessment (0–4 hours)" },
      { type: "p", text: "A dedicated concierge reviews your event brief and cross-references it against the talent's current schedule, contractual restrictions, and known preferences. If there's a flag — a conflicting brand endorsement, a blackout date, or a geographic restriction — we identify it immediately and surface alternatives." },
      { type: "h2", text: "Step 2: Initial Inquiry to Management (4–24 hours)" },
      { type: "p", text: "We contact the celebrity's management team with a formal inquiry. This is where our relationships matter enormously. A cold inquiry from an unknown party takes weeks. Our standing relationships with over 500 talent agencies means we get responses in hours, not weeks." },
      { type: "h2", text: "Step 3: Negotiation and Contracting (1–5 days)" },
      { type: "p", text: "Once the talent expresses interest, our legal and contracts team works with management to finalise terms — fee, format, rider requirements, usage rights, and cancellation clauses. We protect your interests throughout and flag anything unusual before you sign." },
      { type: "h2", text: "Step 4: Day-Of Coordination" },
      { type: "p", text: "On the event day, a StarBookNow coordinator is on call to manage any last-minute changes. Travel delays, equipment issues, timing adjustments — we handle them so you don't have to. Our goal is a seamless handoff: celebrity to stage, stage to standing ovation." },
    ],
  },
  {
    id: 5,
    title: "From Dubai to Hollywood: Why Global Brands Are Turning to Regional Stars",
    slug: "global-brands-regional-celebrity-strategy",
    category: "Strategy",
    author: "Priya Mehta",
    authorRole: "Head of Client Experience",
    date: "2026-01-15",
    readTime: "8 min read",
    feat: false,
    img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80",
    excerpt: "Hollywood mega-stars are no longer the default choice for international brands. Regional celebrity strategy is delivering better ROI — and the numbers are hard to argue with.",
    content: [
      { type: "p", text: "For decades, the prestige of a global campaign was measured by the fame of its ambassador. Hollywood. Premier League. Grand Slam. The bigger the name, the better the brief. But marketing data from the last three years tells a different story — and the most sophisticated brand teams are listening." },
      { type: "h2", text: "The Trust Premium of Regional Stars" },
      { type: "p", text: "Audiences in the Gulf, Southeast Asia, and Sub-Saharan Africa consistently report higher trust in locally-recognised celebrities than in international imports. A familiar face from their culture, speaking their language, reflecting their values, carries authenticity that no media budget can manufacture." },
      { type: "h2", text: "The Cost-Efficiency Argument" },
      { type: "p", text: "A tier-1 Hollywood star might command fees that consume the entirety of a mid-sized brand's annual marketing budget — for a single campaign. A regional star with equivalent cultural influence in the target market can deliver comparable impact at a fraction of the cost, leaving budget for production quality and distribution." },
      { type: "h2", text: "Building a Balanced Roster Strategy" },
      { type: "p", text: "The most effective global brands are building layered celebrity strategies: one globally-recognised anchor ambassador for brand prestige, supported by a roster of regional talent for market-specific activation. StarBookNow's international roster across 40+ countries makes this strategy accessible to brands of any size." },
    ],
  },
  {
    id: 6,
    title: "Meet & Greet Masterclass: How to Create a VIP Fan Experience That People Actually Remember",
    slug: "meet-greet-vip-fan-experience",
    category: "Event Planning",
    author: "Marcus Cole",
    authorRole: "Talent Relations Director",
    date: "2025-12-20",
    readTime: "5 min read",
    feat: false,
    img: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=1200&q=80",
    excerpt: "A meet & greet is only as good as its execution. These are the details that transform a quick photo opportunity into a moment fans carry with them for a year.",
    content: [
      { type: "p", text: "Meet & greets have a variable reputation. At their worst, they're rushed, impersonal, and leave fans feeling like items on a conveyor belt. At their best, they're transformative — a moment of genuine human connection with someone whose work has meant something to you. The difference is almost entirely in the execution details." },
      { type: "h2", text: "Flow Architecture" },
      { type: "p", text: "The physical flow of the meet & greet space determines the experience quality more than almost any other factor. Queuing areas should be comfortable, branded, and entertaining. The actual meeting space should feel intimate even when it isn't. Sight lines matter — fans should not be able to see other fans rushing through their moment." },
      { type: "h2", text: "Brief the Celebrity on the Audience" },
      { type: "p", text: "Celebrities who know their audience give better meet & greets. Share demographic data, the context of the event, and any particularly notable attendees (competition winners, long-term superfans, charity beneficiaries). A celebrity who can say 'I heard you've been a fan since the beginning' creates a moment of astonishing personal impact." },
      { type: "h2", text: "Photography Protocol" },
      { type: "p", text: "Professional lighting, a consistent background, and a designated photographer (not a phone-holding fan) produces images that fans will actually want to share. Poor photo quality is one of the most common post-event complaints. Budget for a professional photographer — it is worth every penny." },
      { type: "h2", text: "Post-Event Follow-Through" },
      { type: "p", text: "The experience doesn't end when the fan leaves the room. Sending professional photos within 48 hours, along with a personalised thank-you message from the celebrity (or their team), extends the emotional resonance of the event and drives organic social sharing that money cannot buy." },
    ],
  },
];

export const SPONSORS = [
  { name:"Warner Bros" }, { name:"Universal Pictures" }, { name:"Paramount" },
  { name:"Lionsgate" }, { name:"Sony Music" }, { name:"Universal Music" },
  { name:"Warner Music" }, { name:"Coca-Cola" }, { name:"Rolex" }, { name:"Red Bull" },
];
